pipeline {
	agent any

		tools {
			maven 'maven-3.9.11'
				jdk 'java-21'
		}

	environment {
		TOMCAT_URL = "http://192.168.161.4:8080"
			APP_NAME   = "my-webapp"

			SONAR_HOST_URL = "https://sonarcloud.io"
			SONAR_ORG      = "dso-nkm"      
			SONAR_PROJECT  = "my-webapp"

			ARTIFACTORY_URL = "http://192.168.161.3:8081/artifactory"
			ARTIFACTORY_REPO      = "generic-local"
			USER = "admin"
			PASSWORD = "AP2VxFh7NA2ecg66Jufhg3WYCUa"
			BUILD_NUMBER    = "${env.BUILD_NUMBER}"
	}

	stages {
		stage('Checkout') {
			steps {
				git branch: 'main', url: 'https://github.com/naveenkumarmuppala/myDevOpsProject2025.git'
			}
		}

		stage('Build') {
			steps {
				sh """
					cd my-webapp
					mvn clean package
					"""
			}
			post {
				always {
					jiraSendBuildInfo site: 'naveen-kumar-muppala.atlassian.net'
				} 
			}
		}
		stage('Upload to Artifactory') {
			steps {
				sh '''
					curl -u${USER}:${PASSWORD} -T my-webapp/target/${APP_NAME}.war \
					"${ARTIFACTORY_URL}/${ARTIFACTORY_REPO}/${APP_NAME}/${BUILD_NUMBER}/${APP_NAME}.war"
					'''
			}
		}
	}

	stage('SonarCloud Analysis') {
		steps {
			withCredentials([string(credentialsId: 'sonar-token', variable: 'SONAR_TOKEN')]) {
				sh """
					cd my-webapp
					mvn sonar:sonar \
					-Dsonar.projectKey=${SONAR_PROJECT} \
					-Dsonar.organization=${SONAR_ORG} \
					-Dsonar.host.url=${SONAR_HOST_URL} \
					-Dsonar.login=$SONAR_TOKEN
					"""
			}
		}
	}
	stage('Download from Artifactory') {
		steps {
			sh '''
                                cd my-webapp
				mkdir -p downloaded-artifacts
				curl -u${USER}:${PASSWORD} -O \
				"${ARTIFACTORY_URL}/${ARTIFACTORY_REPO}/${APP_NAME}/${BUILD_NUMBER}/${APP_NAME}.war"
				mv ${APP_NAME}.war downloaded-artifacts/
				'''
		}
	}
	stage('Deploy to Tomcat') {
		steps {
			withCredentials([usernamePassword(credentialsId: 'tomcat-creds', usernameVariable: 'TOMCAT_USER', passwordVariable: 'TOMCAT_PASS')]) {
				sh """
					curl -u $TOMCAT_USER:$TOMCAT_PASS \
					-T my-webapp/downloaded-artifacts/${APP_NAME}.war \
					"$TOMCAT_URL/manager/text/deploy?path=/${APP_NAME}&update=true"
					"""
			}
		}
		post {
			success {
				// send deployment info (include environment info as needed)
				jiraSendDeploymentInfo site: 'naveen-kumar-muppala.atlassian.net',
						       environmentId: 'DSO-3',
						       environmentName: 'development',
						       environmentType: 'development',
						       issueKeys: ['DSO-3']
			}
		}

	}
}
post {
	success {
		script {
			// ✅ Update labels on the issue
			jiraEditIssue(
					site: 'jira-jenkins',
					idOrKey: 'DSO-3',
					issue: [
					fields: [
					labels: ['deployed']
					]
					]
				     )

				// ✅ Transition the issue
				jiraTransitionIssue(
						site: 'jira-jenkins',
						idOrKey: 'DSO-3',
						input: [
						transition: [id: '31']
						]
						)
		}
	}
}
}
