pipeline {
    agent any

    tools {
        maven 'maven-3.9.11'
        jdk 'java-21'
    }

    environment {
        TOMCAT_URL = "http://192.168.161.4:8080"
        APP_NAME   = "my-webapp"

        SONAR_HOST_URL = "https://sonarcloud.io"
        SONAR_ORG      = "DevOps"      
        SONAR_PROJECT  = "dso-nkm"     
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/naveenkumarmuppala/myDevOpsProject2025.git'
            }
        }

        stage('Build') {
            steps {
                sh """
		    cd my-webapp
		    mvn clean package
		"""
            }
        }

        stage('SonarCloud Analysis') {
            steps {
                withCredentials([string(credentialsId: 'sonar-token', variable: 'SONAR_TOKEN')]) {
                    sh """
                       mvn sonar:sonar \
                          -Dsonar.projectKey=${SONAR_PROJECT} \
                          -Dsonar.organization=${SONAR_ORG} \
                          -Dsonar.host.url=${SONAR_HOST_URL} \
                          -Dsonar.login=$SONAR_TOKEN
                    """
                }
            }
        }

        stage('Deploy to Tomcat') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'tomcat-creds', usernameVariable: 'TOMCAT_USER', passwordVariable: 'TOMCAT_PASS')]) {
                    sh """
                        curl -u $TOMCAT_USER:$TOMCAT_PASS \
                        -T target/${APP_NAME}.war \
                        "$TOMCAT_URL/manager/text/deploy?path=/${APP_NAME}&update=true"
                    """
                }
            }
        }
    }
}
